package postgres

import "database/sql"

func Migrate(db *sql.DB) error {
	statements := []string{
		`create table if not exists usage_events (
			id bigserial primary key,
			request_id text,
			event_hash text not null unique,
			timestamp_ms bigint not null,
			timestamp text not null,
			provider text,
			model text not null,
			endpoint text,
			method text,
			path text,
			auth_type text,
			auth_index text,
			source text,
			source_hash text,
			api_key_hash text,
			account_snapshot text,
			auth_label_snapshot text,
			auth_file_snapshot text,
			auth_provider_snapshot text,
			auth_project_id_snapshot text,
			auth_snapshot_at_ms bigint,
			requested_model text,
			resolved_model text,
			reasoning_effort text,
			input_tokens bigint not null default 0,
			output_tokens bigint not null default 0,
			reasoning_tokens bigint not null default 0,
			cached_tokens bigint not null default 0,
			cache_tokens bigint not null default 0,
			cache_read_tokens bigint not null default 0,
			cache_creation_tokens bigint not null default 0,
			total_tokens bigint not null default 0,
			latency_ms bigint,
			ttft_ms bigint,
			failed integer not null default 0,
			fail_status_code integer,
			fail_summary text,
			fail_body text,
			raw_json text,
			created_at_ms bigint not null
		)`,
		`create index if not exists idx_usage_events_timestamp on usage_events(timestamp_ms)`,
		`create index if not exists idx_usage_events_request_id on usage_events(request_id)`,
		`create index if not exists idx_usage_events_model on usage_events(model)`,
		`create index if not exists idx_usage_events_auth_index on usage_events(auth_index)`,
		`create index if not exists idx_usage_events_endpoint on usage_events(endpoint)`,
		`create table if not exists dead_letter_events (
			id bigserial primary key,
			payload text not null,
			error text not null,
			created_at_ms bigint not null
		)`,
		`create table if not exists settings (
			key text primary key,
			value text not null,
			updated_at_ms bigint not null
		)`,
		`create table if not exists model_prices (
			model text primary key,
			prompt_per_1m double precision not null,
			completion_per_1m double precision not null,
			cache_per_1m double precision not null,
			cache_read_per_1m double precision not null default 0,
			cache_creation_per_1m double precision not null default 0,
			source text,
			source_model_id text,
			raw_json text,
			updated_at_ms bigint not null,
			synced_at_ms bigint
		)`,
		`create table if not exists api_key_aliases (
			api_key_hash text primary key,
			alias text not null,
			updated_at_ms bigint not null
		)`,
		`create table if not exists codex_inspection_runs (
			id bigserial primary key,
			trigger_type text not null,
			trigger_key text,
			status text not null,
			started_at_ms bigint not null,
			finished_at_ms bigint,
			total_files integer not null default 0,
			probe_set_count integer not null default 0,
			sampled_count integer not null default 0,
			disabled_count integer not null default 0,
			enabled_count integer not null default 0,
			delete_count integer not null default 0,
			disable_count integer not null default 0,
			enable_count integer not null default 0,
			reauth_count integer not null default 0,
			keep_count integer not null default 0,
			error text,
			settings_json text not null,
			created_at_ms bigint not null,
			updated_at_ms bigint not null
		)`,
		`create index if not exists idx_codex_inspection_runs_started_at on codex_inspection_runs(started_at_ms)`,
		`create index if not exists idx_codex_inspection_runs_status on codex_inspection_runs(status)`,
		`create index if not exists idx_codex_inspection_runs_trigger on codex_inspection_runs(trigger_type, trigger_key)`,
		`create table if not exists codex_inspection_results (
			id bigserial primary key,
			run_id bigint not null,
			account_key text not null,
			file_name text not null,
			display_account text not null,
			auth_index text,
			account_id text,
			provider text,
			disabled integer not null default 0,
			status text,
			state text,
			action text not null,
			action_reason text,
			action_status text,
			executed_action text,
			action_error text,
			status_code integer,
			used_percent double precision,
			is_quota integer not null default 0,
			error text,
			created_at_ms bigint not null,
			foreign key(run_id) references codex_inspection_runs(id) on delete cascade,
			unique(run_id, account_key)
		)`,
		`create index if not exists idx_codex_inspection_results_run on codex_inspection_results(run_id)`,
		`create table if not exists codex_inspection_logs (
			id bigserial primary key,
			run_id bigint not null,
			level text not null,
			message text not null,
			detail_json text,
			created_at_ms bigint not null,
			foreign key(run_id) references codex_inspection_runs(id) on delete cascade
		)`,
		`create index if not exists idx_codex_inspection_logs_run on codex_inspection_logs(run_id, created_at_ms)`,
		`alter table codex_inspection_runs add column if not exists reauth_count integer not null default 0`,
		`alter table codex_inspection_results add column if not exists action_status text`,
		`alter table codex_inspection_results add column if not exists executed_action text`,
		`alter table codex_inspection_results add column if not exists action_error text`,
		`alter table usage_events add column if not exists account_snapshot text`,
		`alter table usage_events add column if not exists auth_label_snapshot text`,
		`alter table usage_events add column if not exists auth_file_snapshot text`,
		`alter table usage_events add column if not exists auth_provider_snapshot text`,
		`alter table usage_events add column if not exists auth_project_id_snapshot text`,
		`alter table usage_events add column if not exists auth_snapshot_at_ms bigint`,
		`alter table usage_events add column if not exists requested_model text`,
		`alter table usage_events add column if not exists resolved_model text`,
		`alter table usage_events add column if not exists reasoning_effort text`,
		`alter table usage_events add column if not exists cache_read_tokens bigint not null default 0`,
		`alter table usage_events add column if not exists cache_creation_tokens bigint not null default 0`,
		`alter table usage_events add column if not exists ttft_ms bigint`,
		`alter table usage_events add column if not exists fail_status_code integer`,
		`alter table usage_events add column if not exists fail_summary text`,
		`alter table usage_events add column if not exists fail_body text`,
		`alter table model_prices add column if not exists cache_read_per_1m double precision not null default 0`,
		`alter table model_prices add column if not exists cache_creation_per_1m double precision not null default 0`,
	}
	for _, statement := range statements {
		if _, err := db.Exec(statement); err != nil {
			return err
		}
	}
	return nil
}
